# This file was generated by GoReleaser. DO NOT EDIT.
cask "worksome" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "6220ffb7142031868c8f0540c4ea9ce8381736a7b7d8ed4dd6392dea0380d48f"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8a296ea6100904eaf4f7b847283185257329cedd4da74bcf49946788716a9ef"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "99577550f8f4d7bc6858fcf584f8cf581839a5bc09d1605bfc61e7b36ca6a883"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1abee70f5f4595b06ab99e5c3fe503931e61229cad536c0c3dac00665757cb01"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_linux_amd64.tar.gz"
    end
  end

  name "worksome"
  desc "CLI for the Worksome API"
  homepage "https://github.com/worksome/worksome-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "worksome"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/worksome"]
    end
  end

  # No zap stanza required
end
