# This file was generated by GoReleaser. DO NOT EDIT.
cask "worksome" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "ce0ead8b5fcb9eec0a690ac893d9118a9a602c6432537b3b9456b344cb06e622"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d7f0bfcd35f2660e67ec9cdc917839bc6cdac8e4c3e77e6ef5c1efad9eaff77"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8c031dfed6533c739b0ddc16e7999d8fafe4e295a32d9726061c4850f6346edc"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a7cb3f3af9aefd5dea6a153323f0ab363ee29916cdc7e29403e5fac534d90d6"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_linux_amd64.tar.gz"
    end
  end

  name "worksome"
  desc "CLI for the Worksome API"
  homepage "https://github.com/worksome/worksome-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "worksome"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/worksome"]
    end
  end

  # No zap stanza required
end
