# This file was generated by GoReleaser. DO NOT EDIT.
cask "worksome" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "0ae48816fa00a9d3c799e6697195f3951c620750fc70f540b7116d5575767ac2"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "304249bf9af4a5ba157f6b2338e107368a86cdf11049dd7359734900a4f6a28e"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c76c489917d437a98543bdeca46411b332029d27d7edda00c2279b53dc7e2424"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "96025667dbbb4b21337122733a13a34a708eb4768d35b94fc8aec406262bb19b"
      url "https://github.com/worksome/worksome-cli/releases/download/v#{version}/worksome_linux_amd64.tar.gz"
    end
  end

  name "worksome"
  desc "CLI for the Worksome API"
  homepage "https://github.com/worksome/worksome-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "worksome"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/worksome"]
    end
  end

  # No zap stanza required
end
